# open the file manager
sort_order = ["Nordic Kinetics ğŸ§‘â€âš•ï¸"]
blacklist = ["scratch"]
[[session]]
name = "Nordic Kinetics ğŸ§‘â€âš•ï¸"
path = "~/nk/nordic-kinetics"
windows = ["web", "app"]

[[window]]
name = "web"
path = "~/nk/nordic-kinetics"
[[window]]
name = "app"
path = "~/nk/nordic-kinetics"


[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
#startup_command = "yazi"

[[session]]
name = "Obsidian ğŸ’"
path = "~/Documents/second-brain/"
startup_command = "vim"

# open a file
[[session]]
name = "tmux config ğŸ› ï¸"
path = "~/.config/tmux/"
startup_command = "nvim tmux.conf"

[[session]]
name = "Sesh config ğŸ› ï¸"
path = "~/.config/sesh/"
startup_command = "nvim sesh.toml"

[[session]]
name = "Wezterm ğŸ–¥ï¸"
path = "~/.config/wezterm/"
startup_command = "nvim wezterm.lua"

[[session]]
name = "Aerospace âœˆï¸"
path = "~/.config/aerospace/"
startup_command = "nvim aerospace.toml"
[[session]]
name = "Multi Host Router ğŸš§"
path = "~/my-projects/traefik-multi-host-mapper/"
startup_command = "nvim config.toml"

[[session]]
name = "Dua"
path = "/"
startup_command = "dua i"


[[session]]
name = "Dotfiles ğŸ§‘â€ğŸ’»"
path = "~"
startup_command = "nvim README.md"
