# open the file manager

blacklist = ["scratch"]
[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Obsidian ğŸ’"
path = "~/Documents/second-brain/"
startup_command = "vim"

# open a file
[[session]]
name = "tmux config ğŸ› ï¸"
path = "~/.config/tmux/"
startup_command = "nvim tmux.conf"

[[session]]
name = "Sesh config ğŸ› ï¸"
path = "~/.config/sesh/"
startup_command = "nvim sesh.toml"

[[session]]
name = "Wezterm ğŸ–¥ï¸"
path = "~/.config/wezterm/"
startup_command = "nvim wezterm.lua"

[[session]]
name = "Dua"
path = "/"
startup_command = "dua i"
